# Generated by Django 4.2.1 on 2023-05-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='lon',
            field=models.FloatField(),
        ),
    ]
